# Generated by Django 3.2.7 on 2021-11-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='no')),
                ('media_type', models.CharField(max_length=50, verbose_name='media_type')),
                ('contentCd', models.IntegerField(verbose_name='contentCd')),
                ('writer', models.CharField(max_length=30, null=True, verbose_name='writer')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('note', models.CharField(max_length=1024, verbose_name='note')),
                ('image', models.CharField(max_length=1024, verbose_name='image')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='regdate')),
                ('usage', models.CharField(max_length=10, verbose_name='usage')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='id')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('passwd', models.CharField(max_length=30, verbose_name='passwd')),
                ('gender', models.CharField(choices=[('여자', '여자'), ('남자', '남자'), ('퀴어', '퀴어')], max_length=20, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
                ('pg_romance', models.BooleanField(default=False)),
                ('pg_thriller', models.BooleanField(default=False)),
                ('pg_horror', models.BooleanField(default=False)),
                ('pg_noir', models.BooleanField(default=False)),
                ('pg_action', models.BooleanField(default=False)),
                ('pg_sf', models.BooleanField(default=False)),
                ('pg_fantasy', models.BooleanField(default=False)),
                ('pg_teen', models.BooleanField(default=False)),
                ('pg_anime', models.BooleanField(default=False)),
                ('pg_history', models.BooleanField(default=False)),
                ('pg_sports', models.BooleanField(default=False)),
                ('pg_music', models.BooleanField(default=False)),
                ('pg_comedy', models.BooleanField(default=False)),
                ('pg_war', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True, verbose_name='num')),
                ('media_type', models.CharField(max_length=30, verbose_name='media_type')),
                ('contentCd', models.IntegerField(verbose_name='contentCd')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('writer', models.CharField(max_length=30, verbose_name='writer')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='regdate')),
                ('sympathy', models.IntegerField(default=0, verbose_name='sympathy')),
                ('readcount', models.IntegerField(default=0, verbose_name='readcount')),
                ('ip', models.CharField(max_length=20, verbose_name='IP')),
                ('passwd2', models.CharField(default='', max_length=30, verbose_name='passwd2')),
            ],
        ),
    ]
