# Generated by Django 3.2.7 on 2021-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igobazoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alnum', models.IntegerField(unique=True, verbose_name='번호')),
                ('alid', models.CharField(max_length=30, verbose_name='아이디')),
                ('peopleCd', models.CharField(max_length=30, verbose_name='배우')),
                ('modacldate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlnum', models.IntegerField(unique=True, verbose_name='번호')),
                ('dlid', models.CharField(max_length=30, verbose_name='아이디')),
                ('peopleCd', models.CharField(max_length=30, verbose_name='감독')),
                ('moddrldate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlnum', models.IntegerField(unique=True, verbose_name='번호')),
                ('mlid', models.CharField(max_length=30, verbose_name='아이디')),
                ('contentCd', models.IntegerField(default=0, verbose_name='영화코드')),
                ('modmvldate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
